### ISSUE TITLE
Epic: Site owner managing products and tracking orders

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/wgr-store#1]
As a **site owner** I would like **manage the products available to the user** and **track user orders and sales information** to enable me to ** effectively manage my business**.

## Tasks
- [ ]  chrissuttondev/wgr-store#10 
- [ ] chrissuttondev/wgr-store#5 
- [ ] chrissuttondev/wgr-store#9 
- [ ] chrissuttondev/wgr-store#8
