### ISSUE TITLE
User Story: User Sign in

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/wgr-store#14]
As a **customer**, I would like to **sign in to my account** to enable me to **saved preferences, view order history, and proceed with purchases**.

Acceptance Criteria:

The website should display a "Sign In" option on the homepage or header.

When clicking "Sign In," users should be directed to a login page where they can enter their email and password.

After successful sign-in, users should be redirected to their account dashboard or the page they were previously on.

## Tasks
- [x] Create a sign in link clearly visible in header/ navigation of the website
- [x] Create a sign in form for user to input details
- [x] Implement form validation to ensure fields completed 
- [x] Display error messages if unknown / incorrect details are inputted by the user
- [x] Test functionality

**Comment by chrissuttondev** [comment]
Tested in development mode only. Testing post deployment required.
