### ISSUE TITLE
User Story: Searching Products

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/wgr-store#20]
As a **customer**, I would like to **search for specific products** to enable me to **quickly find what I’m looking for**.

Acceptance Criteria:

The search bar should be easily accessible from any page on the website.

Typing in a product name or keyword and hitting enter should display relevant search results.

## Tasks

- [x] Create visually appealing search bar, displayed in header or on products page
- [x] Create models, views and html template to view products in search results
- [x] Implement logic to handle user search queries

**Comment by chrissuttondev** [comment]
Searching products is functional, but perhaps not detailed enough. For example, if as user searches 'men's' no results are yield. If a a user searches 'mens' (without the apostrophe) then Men's and Women's clothing are displayed in the search results.
