### ISSUE TITLE
User Story: Viewing products 

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/wgr-store#21]
As a **customer**, I would like to **view all of the  products available on the website** to enable me to **explore the full range of goods**.

Acceptance Criteria:

The homepage should clearly  display a "View All Products" or “Browse Range” button or link .

Clicking on the "View All Products" option should lead the user to a page displaying all available products.

There should be options to filter and sort products based on things like price, popularity, or category.

## Tasks
- [x] Create wirferames for UI 
- [x] Create home and product apps
- [x] Create base html and CSS
- [x] Create html product page template and CSS
- [x] Code model and view for the products
- [x] Add products data to the database
- [x] Test functionality
