### ISSUE TITLE
Epic: Select items and checkout

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/wgr-store#4]
As a **user** I would like to **add products to a shopping cart and checkout securely** so that I can **quickly and easily purchase the products I want**

Acceptance criteria in Tasks

## Tasks
- [ ] chrissuttondev/William-George-Retail-ltd#34 
- [ ] chrissuttondev/William-George-Retail-ltd#33 
- [ ] chrissuttondev/William-George-Retail-ltd#32 
- [ ] chrissuttondev/William-George-Retail-ltd#31 
- [ ] chrissuttondev/William-George-Retail-ltd#26
