### ISSUE TITLE
Epic User Story: Authentication

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/wgr-store#7]
As a user , I am directed to authenticate and/or register when coming to the website.

Acceptance Criteria within tasks.

## Task
- [x] chrissuttondev/wgr-store#15 
- [x] chrissuttondev/wgr-store#14 
- [x] chrissuttondev/wgr-store#13 
- [x] chrissuttondev/wgr-store#12
